# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'QRCodeDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for QRCodeDemo

  target 'QRCodeDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'QRCodeDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end
   pod 'AFNetworking'
   pod 'MBProgressHUD'
   pod 'Masonry'
end
